name: Deploy HTML App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: "index.html"
          output_path: "./lighthouse-report"
          settings: '{"onlyCategories": ["accessibility", "best-practices", "performance"]}'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 
